支持PHP8
overtrue/http pull request #29
Opened 2022-02-17 15:57 UTC by skys215

修复了[__set_state](https://www.php.net/manual/zh/language.oop5.magic.php#object.set-state)不符合php8的问题

https://github.com/overtrue/http/issues/22

2022-02-17 16:20 UTC, overtrue requested changes

2022-02-17 16:20 UTC, overtrue commented on src/Support/Collection.php
> +            $obj->{$k} = $v;
obj哪里来的？

2022-02-18 03:22 UTC, skys215 commented on src/Support/Collection.php
> +            $obj->{$k} = $v;
尴尬，漏了
已补充

2022-02-19 01:43 UTC, overtrue commented on src/Support/Collection.php
> +            $obj->{$k} = $v;
你的写法还是不对，我改了一下

2022-02-19 01:59 UTC, merged